apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: null
  generation: 1
  labels:
    run: airflow-worker
  name: airflow-worker
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/airflow-worker
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: airflow-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: airflow-worker
    spec:
      containers:
      - args:
        - worker
        env:
        - name: GCS_BUCKET
          value: GCS_BUCKET
        - name: GCP_PROJECT
          value: GCP_PROJECT
        - name: COMPOSER_LOCATION
          value: COMPOSER_LOCATION
        - name: COMPOSER_ENVIRONMENT
          value: COMPOSER_ENVIRONMENT
        - name: AIRFLOW_HOME
          value: /etc/airflow
        - name: DAGS_FOLDER
          value: /home/airflow/gcs/dags
        - name: SQL_DATABASE
          value: airflow-db
        - name: SQL_USER
          value: root
        - name: SQL_PASSWORD
        - name: AIRFLOW__WEBSERVER__BASE_URL
          value: AIRFLOW__WEBSERVER__BASE_URL
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: mysql+mysqldb://$(SQL_USER):$(SQL_PASSWORD)@airflow-sqlproxy-service/$(SQL_DATABASE)
        - name: C_FORCE_ROOT
          value: "TRUE"
        image: gcr.io/IMAGE
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - python
            - /var/local/worker_checker.py
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 120
          successThreshold: 1
          timeoutSeconds: 1
        name: airflow-worker
        ports:
        - containerPort: 8793
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/airflow/airflow_cfg
          name: airflow-config
        - mountPath: /home/airflow/gcs
          name: gcsdir
      - args:
        - /home/airflow/gcs
        env:
        - name: GCS_BUCKET
          value: GCS_BUCKET
        image: gcr.io/cloud-airflow-releaser/gcs-syncd:cloud_composer_service_2018-05-10-RC0
        imagePullPolicy: IfNotPresent
        name: gcs-syncd
        resources:
          requests:
            cpu: 10m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/airflow/gcs
          name: gcsdir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: airflow-configmap
        name: airflow-config
      - emptyDir: {}
        name: gcsdir
status: {}
